import {
  Building2,
  Calendar,
  Layers,
  BookOpen,
  GitBranch,
  Shield,
  Clock,
  CalendarCheck,
  FileText,
  Award,
  Users,
  UserCheck,
  KeyRound,
  Mail,
  Bell,
  Printer,
  UploadCloud,
  DownloadCloud,
  Sliders,
  Sparkles,
  Lock,
  Smartphone,
  RotateCcw,
  CheckCircle2,
  FolderKanban,
  Hash,
  Home,
  LayoutDashboard,
  Palette,
} from 'lucide-react';

export interface SettingsNavItem {
  id: string;
  title: string;
  href: string;
  icon: any;
  description: string;
  category: string;
  keywords: string[];
}

export interface SettingsCategoryGroup {
  category: string;
  label: string;
  items: SettingsNavItem[];
}

export const SETTINGS_NAVIGATION_GROUPS: SettingsCategoryGroup[] = [
  {
    category: 'GENERAL',
    label: 'General',
    items: [
      {
        id: 'overview',
        title: 'Overview',
        href: '/school/settings',
        icon: LayoutDashboard,
        description: 'System configuration status, readiness indicators & quick setup',
        category: 'GENERAL',
        keywords: ['overview', 'status', 'health', 'readiness', 'dashboard', 'settings'],
      },
      {
        id: 'school-profile',
        title: 'School Profile',
        href: '/school/settings/school-profile',
        icon: Building2,
        description: 'Official institution identity, registration, affiliation and contact info',
        category: 'GENERAL',
        keywords: ['profile', 'identity', 'name', 'address', 'contact', 'code', 'affiliation', 'board'],
      },
      {
        id: 'campuses',
        title: 'Campuses',
        href: '/school/settings/campuses',
        icon: Home,
        description: 'Multi-campus site registration, location codes and branch management',
        category: 'GENERAL',
        keywords: ['campuses', 'branches', 'sites', 'locations', 'buildings', 'campus'],
      },
      {
        id: 'branding',
        title: 'Branding',
        href: '/school/settings/branding',
        icon: Palette,
        description: 'Institutional seals, official signatures, primary logos and document watermarks',
        category: 'GENERAL',
        keywords: ['branding', 'logo', 'seal', 'signature', 'crest', 'watermark', 'theme'],
      },
      {
        id: 'id-system',
        title: 'ID System & Formats',
        href: '/school/settings/id-system',
        icon: Hash,
        description: 'Auto-generation rules, prefixes and number sequences for Students, Teachers and Staff',
        category: 'GENERAL',
        keywords: ['id', 'student id', 'teacher id', 'employee id', 'admission number', 'format', 'prefix', 'sequence', 'auto id'],
      },
    ],
  },
  {
    category: 'ACADEMIC',
    label: 'Academic',
    items: [
      {
        id: 'academic-sessions',
        title: 'Academic Sessions',
        href: '/school/settings/academic-sessions',
        icon: Calendar,
        description: 'Academic years, active term calendar dates and session lifecycle',
        category: 'ACADEMIC',
        keywords: ['sessions', 'academic years', 'calendar', 'dates', 'terms', 'session'],
      },
      {
        id: 'classes',
        title: 'Classes',
        href: '/school/settings/classes',
        icon: Layers,
        description: 'Class cohorts, grade levels and institutional standard rosters',
        category: 'ACADEMIC',
        keywords: ['classes', 'grades', 'cohorts', 'levels', 'standards'],
      },
      {
        id: 'sections',
        title: 'Sections',
        href: '/school/settings/sections',
        icon: FolderKanban,
        description: 'Relational division sections, room assignments and capacity thresholds',
        category: 'ACADEMIC',
        keywords: ['sections', 'divisions', 'rooms', 'capacity', 'student count'],
      },
      {
        id: 'subjects',
        title: 'Subjects',
        href: '/school/settings/subjects',
        icon: BookOpen,
        description: 'Curriculum subjects, syllabus codes, subject types and teaching quotas',
        category: 'ACADEMIC',
        keywords: ['subjects', 'courses', 'curriculum', 'codes', 'departments'],
      },
      {
        id: 'streams',
        title: 'Streams',
        href: '/school/settings/streams',
        icon: GitBranch,
        description: 'Senior secondary academic streams for Class 11 and Class 12 tracks',
        category: 'ACADEMIC',
        keywords: ['streams', 'tracks', 'science', 'commerce', 'humanities', 'class 11', 'class 12'],
      },
      {
        id: 'houses',
        title: 'Houses',
        href: '/school/settings/houses',
        icon: Sparkles,
        description: 'Optional co-curricular student houses, colors and motto assignments',
        category: 'ACADEMIC',
        keywords: ['houses', 'teams', 'house system', 'colors', 'extracurricular'],
      },
      {
        id: 'roll-numbers',
        title: 'Roll Number Management',
        href: '/school/settings/roll-numbers',
        icon: Hash,
        description: 'Dual numbering rules: Class roll call basis and Exam roll generation policies',
        category: 'ACADEMIC',
        keywords: ['roll numbers', 'allocation', 'exam roll', 'class roll', 'dual roll', 'numbering'],
      },
    ],
  },
  {
    category: 'OPERATIONS',
    label: 'School Operations',
    items: [
      {
        id: 'attendance',
        title: 'Attendance',
        href: '/school/settings/attendance',
        icon: CalendarCheck,
        description: 'Marking permissions, record lock periods and active attendance status options',
        category: 'OPERATIONS',
        keywords: ['attendance', 'roll call', 'marking', 'lock', 'absent', 'present', 'rules'],
      },
      {
        id: 'timetable',
        title: 'Timetable',
        href: '/school/settings/timetable',
        icon: Clock,
        description: 'Working days, bell schedules, period intervals and automated conflict checks',
        category: 'OPERATIONS',
        keywords: ['timetable', 'periods', 'schedule', 'bell', 'intervals', 'conflict detection', 'rooms'],
      },
      {
        id: 'homework',
        title: 'Homework',
        href: '/school/settings/homework',
        icon: FileText,
        description: 'Assignment creation permissions, submission tracking and parent visibility',
        category: 'OPERATIONS',
        keywords: ['homework', 'assignments', 'tasks', 'submissions', 'deadlines', 'attachments'],
      },
      {
        id: 'examinations',
        title: 'Examinations',
        href: '/school/settings/examinations',
        icon: Award,
        description: 'Assessment categories, timetable slots, grading scales, halls and conduct rules',
        category: 'OPERATIONS',
        keywords: ['examinations', 'exams', 'assessment', 'grading', 'time slots', 'exam types', 'rooms'],
      },
      {
        id: 'results',
        title: 'Results',
        href: '/school/settings/results',
        icon: CheckCircle2,
        description: 'Consolidated result publishing behavior, student portal access and result locking',
        category: 'OPERATIONS',
        keywords: ['results', 'publishing', 'marksheet', 'report cards', 'grades', 'visibility'],
      },
    ],
  },
  {
    category: 'PEOPLE',
    label: 'People & Access',
    items: [
      {
        id: 'users',
        title: 'Users',
        href: '/school/settings/users',
        icon: Users,
        description: 'Staff, faculty and administrator user accounts and credentials status',
        category: 'PEOPLE',
        keywords: ['users', 'accounts', 'directory', 'staff', 'faculty', 'admins', 'profiles'],
      },
      {
        id: 'roles',
        title: 'Roles',
        href: '/school/settings/roles',
        icon: UserCheck,
        description: 'System standard security roles and custom institutional responsibilities',
        category: 'PEOPLE',
        keywords: ['roles', 'school admin', 'teacher', 'student', 'parent', 'custom roles'],
      },
      {
        id: 'permissions',
        title: 'Permissions',
        href: '/school/settings/permissions',
        icon: KeyRound,
        description: 'Granular role action matrix across viewing, authoring, publishing and exporting',
        category: 'PEOPLE',
        keywords: ['permissions', 'matrix', 'access control', 'privileges', 'read', 'write', 'scope'],
      },
      {
        id: 'invitations',
        title: 'Invitations',
        href: '/school/settings/invitations',
        icon: Mail,
        description: 'Pending onboarding invites, activation token expiry and revocations',
        category: 'PEOPLE',
        keywords: ['invitations', 'invite', 'onboarding', 'activation', 'tokens', 'pending'],
      },
    ],
  },
  {
    category: 'SECURITY',
    label: 'Security & Auth',
    items: [
      {
        id: 'authentication',
        title: 'Authentication',
        href: '/school/settings/security/authentication',
        icon: Lock,
        description: 'Password authentication, identity provider status and session timeout window',
        category: 'SECURITY',
        keywords: ['authentication', 'auth', 'login', 'credentials', 'timeout', 'role access'],
      },
      {
        id: 'password-policy',
        title: 'Password Policy',
        href: '/school/settings/security/password-policy',
        icon: Shield,
        description: 'Complexity rules, minimum length, symbol requirements and credential security',
        category: 'SECURITY',
        keywords: ['password policy', 'complexity', 'security', 'length', 'expiration'],
      },
      {
        id: 'sessions',
        title: 'Sessions',
        href: '/school/settings/security/sessions',
        icon: Smartphone,
        description: 'Active sign-in sessions, device footprint and emergency global sign-out',
        category: 'SECURITY',
        keywords: ['sessions', 'devices', 'browsers', 'revoke', 'active logins', 'sign out'],
      },
      {
        id: 'mfa',
        title: 'Multi-Factor Auth',
        href: '/school/settings/security/mfa',
        icon: Shield,
        description: 'MFA integration status, administrator requirement policy and readiness',
        category: 'SECURITY',
        keywords: ['mfa', 'two-factor', '2fa', 'otp', 'authenticator', 'security'],
      },
      {
        id: 'recovery',
        title: 'Account Recovery',
        href: '/school/settings/security/recovery',
        icon: RotateCcw,
        description: 'Self-service password recovery options and administrative reset mechanisms',
        category: 'SECURITY',
        keywords: ['recovery', 'forgot password', 'reset', 'account recovery', 'tokens'],
      },
    ],
  },
  {
    category: 'COMMUNICATION',
    label: 'Communication',
    items: [
      {
        id: 'notices',
        title: 'Notices',
        href: '/school/settings/notices',
        icon: FileText,
        description: 'Broadcast circular permissions, audience targets and publishing schedule controls',
        category: 'COMMUNICATION',
        keywords: ['notices', 'circulars', 'broadcast', 'announcements', 'publishing'],
      },
      {
        id: 'notifications',
        title: 'Notifications',
        href: '/school/settings/notifications',
        icon: Bell,
        description: 'Automated event triggers for homework, attendance alerts, exams and results',
        category: 'COMMUNICATION',
        keywords: ['notifications', 'alerts', 'in-app', 'email', 'push', 'events'],
      },
    ],
  },
  {
    category: 'DOCUMENTS',
    label: 'Documents',
    items: [
      {
        id: 'templates',
        title: 'Document Templates',
        href: '/school/settings/documents/templates',
        icon: FileText,
        description: 'Standard institutional templates for Admit Cards, Marksheets and Summaries',
        category: 'DOCUMENTS',
        keywords: ['templates', 'admit card', 'marksheet', 'id card', 'documents', 'certificates'],
      },
      {
        id: 'print-settings',
        title: 'Print Settings',
        href: '/school/settings/documents/print',
        icon: Printer,
        description: 'Official document page dimensions, header margins, seal positioning and signatures',
        category: 'DOCUMENTS',
        keywords: ['print settings', 'page size', 'margins', 'orientation', 'header', 'footer', 'seal'],
      },
    ],
  },
  {
    category: 'DATA',
    label: 'Data',
    items: [
      {
        id: 'import',
        title: 'Import',
        href: '/school/settings/data/import',
        icon: UploadCloud,
        description: 'CSV and spreadsheet onboarding for students, faculty, subjects and classes',
        category: 'DATA',
        keywords: ['import', 'csv', 'spreadsheet', 'data onboarding', 'upload', 'batch'],
      },
      {
        id: 'export',
        title: 'Export',
        href: '/school/settings/data/export',
        icon: DownloadCloud,
        description: 'Download consolidated entity records, exam reports and attendance logs',
        category: 'DATA',
        keywords: ['export', 'download', 'backup', 'csv', 'excel', 'reports'],
      },
    ],
  },
];

export const ALL_SETTINGS_NAV_ITEMS = SETTINGS_NAVIGATION_GROUPS.flatMap((g) => g.items);
